export const mockProjects = [
    {
        id: 1,
        title: 'Grifols-DonorHUB',
        description: 'Comprehensive blood donor management system featuring a scalable Backend API, responsive Web Portal, and robust Mobile Application serving 10,000+ donors securely.',
        shortDescription: 'Full-stack blood donor management platform for 10,000+ users.',
        imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80',
        role: 'Full Stack Software Engineer',
        contribution: 'Architected and built the cross-platform mobile application, responsive web portal, and backend API. Implemented real-time donor registration, scheduling, history tracking, and OAuth2 authentication ensuring HIPAA compliance.',
        technologies: JSON.stringify(['.NET Core', 'ASP.NET Web API', 'Angular', 'TypeScript', 'Flutter', 'Dart', 'OAuth2', 'SQL Server']),
        outcomes: JSON.stringify(['Served 10,000+ donors seamlessly', 'Implemented OAuth2 for HIPAA compliance', 'Delivered cross-device web & mobile parity']),
        category: 'Full Stack',
        featured: 1,
        order: 1,
        caseStudyOverview: 'A comprehensive blood donor management platform designed to streamline the donation process, manage donor records, and ensure HIPAA compliance for a large-scale healthcare provider.',
        problemStatement: 'The client needed a secure, HIPAA-compliant system to manage 10,000+ donors across multiple platforms while reducing manual entry errors and improving scheduling efficiency.',
        solution: 'Developed a unified ecosystem consisting of an Angular web portal, a Flutter mobile app, and a robust .NET Core backend API with OAuth2 authentication.',
        teamSize: 5,
        duration: '8 months (2025)',
    },
    {
        id: 2,
        title: 'Kaizen GYM Management System',
        description: 'Engineered a comprehensive gym management platform across both Backend and Frontend, incorporating Repository, Factory, and MVVM design patterns.',
        shortDescription: 'End-to-end gym administration and member management platform.',
        imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
        role: 'Full Stack Software Engineer',
        contribution: 'Engineered both the backend API and frontend interfaces using ASP.NET Web API and Angular, achieving high responsiveness and solid architectural integrity.',
        technologies: JSON.stringify(['ASP.NET Web API', 'Angular', 'TypeScript', 'Bootstrap', 'Swagger API', 'AutoMapper', 'SQL Server']),
        outcomes: JSON.stringify(['Enhanced member engagement by 40%', 'Applied Repository & Factory design patterns', 'Structured highly responsive frontend']),
        category: 'Full Stack',
        featured: 1,
        order: 2,
        caseStudyOverview: 'An all-in-one gym management solution to replace manual spreadsheets and fragmented tracking systems.',
        problemStatement: 'Gym administrators were struggling with manual member tracking using spreadsheets, leading to frequent billing errors and low engagement.',
        solution: 'Built a responsive Angular dashboard and a .NET Core API utilizing Repository and Factory patterns for high maintainability.',
        teamSize: 3,
        duration: '6 months (2024)',
    },
    {
        id: 3,
        title: 'Tender Management Platform',
        description: 'Designed an enterprise-level tender management platform processing over 200 monthly tenders with robust collaborative API architecture.',
        shortDescription: 'Enterprise platform processing 200+ monthly tenders.',
        imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
        role: 'Backend Developer',
        contribution: 'Designed enterprise-level infrastructure and backend API, implementing robust CI/CD pipelines and comprehensive Swagger documentation.',
        technologies: JSON.stringify(['ASP.NET Web API', 'SQL Server', 'Swagger API', 'CI/CD Pipeline', '.NET Core']),
        outcomes: JSON.stringify(['Processed 200+ monthly tenders efficiently', 'Automated CI/CD deployment pipelines', 'Delivered comprehensive API documentation']),
        category: 'Backend',
        featured: 1,
        order: 3,
        caseStudyOverview: 'A comprehensive enterprise platform for tender management and processing.',
        problemStatement: 'The procurement process was hindered by slow email-based communication and lack of centralized tender tracking.',
        solution: 'Architected a robust backend API with automated CI/CD pipelines and swagger documentation to facilitate seamless collaboration.',
        teamSize: 4,
        duration: '7 months (2023 - 2024)',
    },
    {
        id: 4,
        title: 'Location-Based Attendance System',
        description: 'Full-stack location-based attendance tracker for 100+ staff, matching backend caching to precise GPS mobile verification workflows.',
        shortDescription: 'Geofencing-enabled mobile tracking and backend verification framework.',
        imageUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
        role: 'Full Stack Mobile Developer',
        contribution: 'Developed Flutter mobile app with Geofencing, integrated with an ASP.NET backend using Redis. Architected a PowerApps web-based management layer for attendance tracking.',
        technologies: JSON.stringify(['Flutter', 'Geolocator API', 'Bing Maps API', 'ASP.NET Web API', 'Redis Caching', 'Power Apps']),
        outcomes: JSON.stringify(['Sub-second response times using Redis', 'Precise location verification with GPS', 'Automated management approval workflows']),
        category: 'Mobile',
        featured: 1,
        order: 4,
        caseStudyOverview: 'A geofencing-enabled attendance system for field staff to ensure accurate clock-in/out based on physical location.',
        problemStatement: 'Traditional manual attendance tracking led to inaccuracy and "buddy punching".',
        solution: 'Developed a Flutter app with geofencing integration and a high-performance Redis-backed .NET API.',
        teamSize: 2,
        duration: '4 months (2024)',
    },
    {
        id: 5,
        title: 'Smart Parking System',
        description: 'Built scalable backend infrastructure and a cross-platform mobile application for real-time parking reservations integrated with payment gateways.',
        shortDescription: 'Cross-platform mobile reservation app with payment integration.',
        imageUrl: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80',
        role: 'Full Stack Mobile Developer',
        contribution: 'Built the scalable Entity Framework backend and the iOS/Android Flutter application, orchestrating GPS-based services and payment logic.',
        technologies: JSON.stringify(['Flutter', '.NET Core', 'SQL Server', 'RESTful APIs', 'GPS Integration', 'Payment Gateway']),
        outcomes: JSON.stringify(['Cross-platform iOS & Android launch', 'Real-time space availability tracking', 'Seamless payment processing']),
        category: 'Mobile',
        featured: 0,
        order: 5,
    },
    {
        id: 6,
        title: 'Travel Requisition Workflow Manager',
        description: 'Architected and enhanced a comprehensive travel requisition system across multiple phases. Automated entire workflows from submission to complex approval hierarchies.',
        shortDescription: 'Multi-phase Power Platform travel requisition system.',
        imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
        role: 'Power Platform Developer',
        contribution: 'Automated the end-to-end travel requisition workflow using Power Apps and Power Automate, integrating directly with an Oracle database for financial reporting.',
        technologies: JSON.stringify(['Microsoft Power Apps', 'Power Automate', 'Oracle Database Integration']),
        outcomes: JSON.stringify(['Automated multi-level approval cycles', 'Implemented delegation features', 'Integrated comprehensive financial reporting']),
        category: 'Power Platform',
        featured: 1,
        order: 6,
        caseStudyOverview: 'A comprehensive travel requisition management system replacing manual paper approvals.',
        problemStatement: 'Travel requests were frequently lost or delayed in manual paperwork chains, costing time and money.',
        solution: 'Developed a full-lifecycle digital approval workflow mapping complex corporate hierarchies.',
        teamSize: 2,
        duration: '5 months (2024 - 2025)',
    },
    {
        id: 7,
        title: 'Fire Safety Maintenance Application',
        description: 'Created a digital solution for fire safety equipment maintenance traceability across 50+ facilities with automated notification systems.',
        shortDescription: 'Facility fire safety inspection and maintenance tracker.',
        imageUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c848?w=1200&q=80',
        role: 'Power Platform Developer',
        contribution: 'Designed a SharePoint and Power Apps ecosystem to track fire safety measures, implementing automated notifications for tight regulatory adherence.',
        technologies: JSON.stringify(['SharePoint', 'Power Automate', 'Power Apps']),
        outcomes: JSON.stringify(['Tracked maintenance across 50+ facilities', 'Automated regulatory compliance checks', 'Delivered automated notification workflows']),
        category: 'Power Platform',
        featured: 0,
        order: 7,
    },
    {
        id: 8,
        title: 'Price Fluctuation Workflow Manager',
        description: 'Engineered a dynamic approval workflow for price change authorizations, streamlining pricing decision-making processes to maintain business continuity.',
        shortDescription: 'Automated workflow for price change authorizations.',
        imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
        role: 'Power Platform Developer',
        contribution: 'Engineered dynamic approval workflows for tracking price changes across services, supporting uninterrupted business operations.',
        technologies: JSON.stringify(['SharePoint', 'Power Automate', 'Power Apps']),
        outcomes: JSON.stringify(['Automated multi-level approval cycles', 'Real-time notifications integration', 'Streamlined core pricing decisions']),
        category: 'Power Platform',
        featured: 0,
        order: 8,
    },
    {
        id: 9,
        title: 'Custody & Expenses Management App',
        description: 'Developed a comprehensive expense management system with automated workflows, creating transparent expense tracking with strong financial controls.',
        shortDescription: 'Automated expense tracking and financial controls application.',
        imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
        role: 'Power Platform Developer',
        contribution: 'Developed an automated system for recording, reviewing, and authorizing financial custody limits and employee expenses.',
        technologies: JSON.stringify(['SharePoint', 'Power Automate', 'Power Apps']),
        outcomes: JSON.stringify(['Enhanced financial transparency', 'Automated expense reimbursements', 'Established comprehensive audit trails']),
        category: 'Power Platform',
        featured: 0,
        order: 9,
    },
    {
        id: 10,
        title: 'Departmental Correspondence',
        description: 'Built a centralized digital communication platform for departmental correspondence tracking, routing, and centralized document version control.',
        shortDescription: 'Centralized departmental communication platform.',
        imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
        role: 'Power Platform Developer',
        contribution: 'Developed a robust document management app enhancing interdepartmental communication through automated routing and stringent version control.',
        technologies: JSON.stringify(['SharePoint', 'Power Automate', 'Power Apps']),
        outcomes: JSON.stringify(['Centralized interdepartmental communication', 'Automated secure document routing', 'Enforced document version control']),
        category: 'Power Platform',
        featured: 0,
        order: 10,
    }
];

export const mockExperiences = [
    {
        id: 1,
        title: 'Software Engineer',
        company: 'Information Technology of Egypt Corporation',
        location: 'Giza, Egypt',
        startDate: new Date('2022-09-01').toISOString(),
        endDate: null,
        description: 'Led full-stack development initiatives across multiple enterprise applications, utilizing .NET Core, Angular, Flutter, and cloud platforms to deliver scalable solutions for business-critical operations.',
        achievements: JSON.stringify([
            'Reduced average API response times by 40% through Redis caching and microservice refactoring, directly improving user satisfaction across web & mobile portals',
            'Implemented end-to-end CI/CD pipelines and unit/integration testing suites, cutting deployment incidents by 70% and accelerating release cadence from weekly to twice-weekly',
            'Led architecture design, API development, and cross-functional delivery for the Tender Management Platform processing 200+ monthly tenders',
            'Built the Grifols DonorHUB backend API, Angular portal, and Flutter app serving 10,000+ donors with OAuth2 authentication for HIPAA compliance',
            'Automated 7 enterprise workflows on Microsoft Power Platform — travel approvals, fire safety compliance across 50+ facilities, price change authorisation, and expense management',
            'Mentored 2 junior engineers and ran weekly clean architecture and testing knowledge-sharing sessions, improving team code quality and reducing peer review cycles'
        ]),
        current: 1,
        order: 1,
    },
    {
        id: 2,
        title: 'IT Specialist',
        company: 'The Breakroom Company',
        location: 'Cairo, Egypt',
        startDate: new Date('2022-06-01').toISOString(),
        endDate: new Date('2022-08-31').toISOString(),
        description: 'Provided comprehensive technical support, administered Odoo ERP system, and performed hardware/software troubleshooting across Windows and Linux environments.',
        achievements: JSON.stringify([
            'Provided technical support and help desk services for 50+ employees with 98% issue resolution rate within SLA',
            'Administered Odoo ERP system including database optimization and user training, achieving 20% improvement in user adoption',
            'Executed hardware and software troubleshooting across Windows and Linux ensuring 99.5% uptime',
            'Successfully orchestrated network configurations and preventative system maintenance frameworks'
        ]),
        current: 0,
        order: 2,
    }
];

export const mockEducation = [
    {
        id: 1,
        degree: 'Bachelor of Science in Computer Science',
        institution: 'Modern Academy',
        field: 'Computer Science',
        startDate: new Date('2017-09-01').toISOString(),
        endDate: new Date('2021-06-30').toISOString(),
        grade: 'Excellent',
        description: 'Relevant Coursework: Data Structures, Algorithms, Database Systems, Software Engineering, Web Development',
        order: 1,
    }
];

export const mockCertifications = [
    { id: 1, name: 'Microsoft Certified: Azure AI Engineer Associate', issuer: 'Microsoft', issuedDate: new Date('2025-06-01').toISOString(), credentialUrl: 'https://learn.microsoft.com/api/credentials/share/en-us/GeorgeVictorKamal-1654/2796F478D3F36F43?sharingId', order: 1 },
    { id: 2, name: 'Microsoft Certified: Power Platform Developer Associate', issuer: 'Microsoft', issuedDate: new Date('2025-02-01').toISOString(), credentialUrl: 'https://learn.microsoft.com/api/credentials/share/en-us/GeorgeVictorKamal-1654/C73F1690A3747C89?sharingId', order: 2 },
    { id: 3, name: 'Introduction to MongoDB', issuer: 'MaharaTech - ITIMooca', issuedDate: new Date('2024-01-01').toISOString(), credentialUrl: 'https://drive.google.com/file/d/1Ha0GX9ULin__Ju8qm5dQcFGfCzYCeGs0/view?usp=drive_link', order: 3 },
    { id: 4, name: 'Intro to ChatGPT and Generative AI', issuer: '365 Data Science', issuedDate: new Date('2023-07-01').toISOString(), credentialUrl: 'https://learn.365datascience.com/c/49a2c9393a', order: 4 },
    { id: 5, name: 'UX Design Fundamentals', issuer: 'MaharaTech - ITIMooca', issuedDate: new Date('2023-04-01').toISOString(), credentialUrl: 'https://drive.google.com/file/d/1FhAl4bvYIGfixj-MFQGbCMP7oee1vke0/view?usp=share_link', order: 5 },
    { id: 6, name: 'Career Essentials in Software Development by Microsoft and LinkedIn', issuer: 'Microsoft', issuedDate: new Date('2023-03-15').toISOString(), credentialUrl: 'https://www.linkedin.com/learning/certificates/cd2380cc04a4da40c26d239a215081acaf49910eec24360b2efb67f04992108e', order: 6 },
    { id: 7, name: 'Learn HTML & CSS', issuer: 'MaharaTech - ITIMooca', issuedDate: new Date('2023-03-01').toISOString(), credentialUrl: 'https://maharatech.gov.eg/mod/customcert/view.php?id=355&downloadown=1', order: 7 },
    { id: 8, name: 'Certified Ethical Hacker (CEH)', issuer: 'MaharaTech - ITIMooca', issuedDate: new Date('2022-12-01').toISOString(), credentialUrl: 'https://drive.google.com/file/d/1OBkTLipP9YbSGL0FJ-aHOaZOYt4XUb9T/view?usp=share_link', order: 8 },
    { id: 9, name: 'Certificate of Completion - SQL', issuer: '365 Data Science', issuedDate: new Date('2022-11-15').toISOString(), credentialUrl: 'https://learn.365datascience.com/c/cc95b5e18c', order: 9 },
    { id: 10, name: 'Introduction to Software Testing Concepts & Techniques', issuer: 'MaharaTech - ITIMooca', issuedDate: new Date('2022-11-01').toISOString(), credentialUrl: 'https://maharatech.gov.eg/mod/customcert/view.php?id=8369&downloadown=1', order: 10 },
    { id: 11, name: 'Global Banking & Markets Virtual Experience Programme', issuer: 'Forage', issuedDate: new Date('2021-08-01').toISOString(), credentialUrl: 'https://www.theforage.com/simulations/jpmorgan-chase/global-banking-markets-8pax', order: 11 },
    { id: 12, name: 'Digital Marketing', issuer: 'EgyptFWD - Udacity', issuedDate: new Date('2021-07-15').toISOString(), credentialUrl: 'https://www.udacity.com/certificate/digital-marketing', order: 12 },
    { id: 13, name: 'Flutter & Dart Development', issuer: 'Udemy', issuedDate: new Date('2021-07-01').toISOString(), credentialUrl: 'https://www.udemy.com/certificate/UC-dbbce24b-c84c-4ba3-9204-dd2848cd9372/', order: 13 },
    { id: 14, name: 'Oracle Database 12c: SQL Fundamentals', issuer: 'Sololearn', issuedDate: new Date('2020-01-01').toISOString(), credentialUrl: 'https://www.sololearn.com/certificates/SQL', order: 14 }
];
